version: "2"
services:
  buildbot:
    build: ./master
    userns_mode: keep-id
    env_file:
      - db.env
    depends_on:
      - db
    volumes:
      - ./master:/data/buildbot
    ports:
      - 8010:8010

  worker_fedora:
    build: ./worker_fedora
    userns_mode: keep-id
    environment:
      BUILDMASTER: buildbot
      WORKERNAME: worker_fedora
      WORKERPASS: pass
    volumes:
      - ./worker_fedora:/data/buildbot
    links:
      - buildbot

  db:
    image: postgres:16
    env_file:
      - db.env
    environment:
      PGDATA: /pg_data
    volumes:
      - PG_DATA:/pg_data
    expose:
      - 5432

  ftp:
    image: drakkan/sftpgo:v2.5.6
    userns_mode: keep-id
    volumes:
      - ./data:/srv/sftpgo
      - FTP_CONF:/var/lib/sftpgo
    ports:
      - 8020:8080

  vault:
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    command: ["vault", "server", "-config=/vault/config.d/"]
    volumes:
      - VAULT_DATA:/vault/file
      - ./vault:/vault/config.d

volumes:
  PG_DATA: {}
  FTP_CONF: {}
  VAULT_DATA: {}
