# -*- coding: utf-8 -*-

"""
    SFTPGo

    SFTPGo allows you to securely share your files over SFTP and optionally over HTTP/S, FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per-user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, a user with the S3 backend mapping a Google Cloud Storage bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo supports groups to simplify the administration of multiple accounts by letting you assign settings once to a group, instead of multiple times to each individual user. The SFTPGo WebClient allows end users to change their credentials, browse and manage their files in the browser and setup two-factor authentication which works with Authy, Google Authenticator and other compatible apps. From the WebClient each authorized user can also create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date.

    The version of the OpenAPI document: 2.5.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, validator
from openapi_client.models.secret import Secret


class AzureBlobFsConfig(BaseModel):
    """
    Azure Blob Storage configuration details
    """

    container: Optional[StrictStr] = None
    account_name: Optional[StrictStr] = Field(
        None, description="Storage Account Name, leave blank to use SAS URL"
    )
    account_key: Optional[Secret] = None
    sas_url: Optional[Secret] = None
    endpoint: Optional[StrictStr] = Field(
        None,
        description='optional endpoint. Default is "blob.core.windows.net". If you use the emulator the endpoint must include the protocol, for example "http://127.0.0.1:10000"',
    )
    upload_part_size: Optional[StrictInt] = Field(
        None,
        description="the buffer size (in MB) to use for multipart uploads. If this value is set to zero, the default value (5MB) will be used.",
    )
    upload_concurrency: Optional[StrictInt] = Field(
        None,
        description="the number of parts to upload in parallel. If this value is set to zero, the default value (5) will be used",
    )
    download_part_size: Optional[StrictInt] = Field(
        None,
        description="the buffer size (in MB) to use for multipart downloads. If this value is set to zero, the default value (5MB) will be used.",
    )
    download_concurrency: Optional[StrictInt] = Field(
        None,
        description="the number of parts to download in parallel. If this value is set to zero, the default value (5) will be used",
    )
    access_tier: Optional[StrictStr] = None
    key_prefix: Optional[StrictStr] = Field(
        None,
        description='key_prefix is similar to a chroot directory for a local filesystem. If specified the user will only see contents that starts with this prefix and so you can restrict access to a specific virtual folder. The prefix, if not empty, must not start with "/" and must end with "/". If empty the whole container contents will be available',
    )
    use_emulator: Optional[StrictBool] = None
    __properties = [
        "container",
        "account_name",
        "account_key",
        "sas_url",
        "endpoint",
        "upload_part_size",
        "upload_concurrency",
        "download_part_size",
        "download_concurrency",
        "access_tier",
        "key_prefix",
        "use_emulator",
    ]

    @validator("access_tier")
    def access_tier_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("", "Archive", "Hot", "Cool"):
            raise ValueError(
                "must be one of enum values ('', 'Archive', 'Hot', 'Cool')"
            )
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AzureBlobFsConfig:
        """Create an instance of AzureBlobFsConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of account_key
        if self.account_key:
            _dict["account_key"] = self.account_key.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sas_url
        if self.sas_url:
            _dict["sas_url"] = self.sas_url.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AzureBlobFsConfig:
        """Create an instance of AzureBlobFsConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AzureBlobFsConfig.parse_obj(obj)

        _obj = AzureBlobFsConfig.parse_obj(
            {
                "container": obj.get("container"),
                "account_name": obj.get("account_name"),
                "account_key": Secret.from_dict(obj.get("account_key"))
                if obj.get("account_key") is not None
                else None,
                "sas_url": Secret.from_dict(obj.get("sas_url"))
                if obj.get("sas_url") is not None
                else None,
                "endpoint": obj.get("endpoint"),
                "upload_part_size": obj.get("upload_part_size"),
                "upload_concurrency": obj.get("upload_concurrency"),
                "download_part_size": obj.get("download_part_size"),
                "download_concurrency": obj.get("download_concurrency"),
                "access_tier": obj.get("access_tier"),
                "key_prefix": obj.get("key_prefix"),
                "use_emulator": obj.get("use_emulator"),
            }
        )
        return _obj
