# -*- coding: utf-8 -*-

"""
    SFTPGo

    SFTPGo allows you to securely share your files over SFTP and optionally over HTTP/S, FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per-user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, a user with the S3 backend mapping a Google Cloud Storage bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo supports groups to simplify the administration of multiple accounts by letting you assign settings once to a group, instead of multiple times to each individual user. The SFTPGo WebClient allows end users to change their credentials, browse and manage their files in the browser and setup two-factor authentication which works with Authy, Google Authenticator and other compatible apps. From the WebClient each authorized user can also create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date.

    The version of the OpenAPI document: 2.5.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBytes, StrictInt, StrictStr
from openapi_client.models.provider_event_action import ProviderEventAction
from openapi_client.models.provider_event_object_type import ProviderEventObjectType


class ProviderEvent(BaseModel):
    """
    ProviderEvent
    """

    id: Optional[StrictStr] = None
    timestamp: Optional[StrictInt] = Field(
        None, description="unix timestamp in nanoseconds"
    )
    action: Optional[ProviderEventAction] = None
    username: Optional[StrictStr] = None
    ip: Optional[StrictStr] = None
    object_type: Optional[ProviderEventObjectType] = None
    object_name: Optional[StrictStr] = None
    object_data: Optional[Union[StrictBytes, StrictStr]] = Field(
        None,
        description="base64 of the JSON serialized object with sensitive fields removed",
    )
    role: Optional[StrictStr] = None
    instance_id: Optional[StrictStr] = None
    __properties = [
        "id",
        "timestamp",
        "action",
        "username",
        "ip",
        "object_type",
        "object_name",
        "object_data",
        "role",
        "instance_id",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProviderEvent:
        """Create an instance of ProviderEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProviderEvent:
        """Create an instance of ProviderEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProviderEvent.parse_obj(obj)

        _obj = ProviderEvent.parse_obj(
            {
                "id": obj.get("id"),
                "timestamp": obj.get("timestamp"),
                "action": obj.get("action"),
                "username": obj.get("username"),
                "ip": obj.get("ip"),
                "object_type": obj.get("object_type"),
                "object_name": obj.get("object_name"),
                "object_data": obj.get("object_data"),
                "role": obj.get("role"),
                "instance_id": obj.get("instance_id"),
            }
        )
        return _obj
