# -*- coding: utf-8 -*-

"""
    SFTPGo

    SFTPGo allows you to securely share your files over SFTP and optionally over HTTP/S, FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per-user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, a user with the S3 backend mapping a Google Cloud Storage bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo supports groups to simplify the administration of multiple accounts by letting you assign settings once to a group, instead of multiple times to each individual user. The SFTPGo WebClient allows end users to change their credentials, browse and manage their files in the browser and setup two-factor authentication which works with Authy, Google Authenticator and other compatible apps. From the WebClient each authorized user can also create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date.

    The version of the OpenAPI document: 2.5.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel
from openapi_client.models.data_provider_status import DataProviderStatus
from openapi_client.models.ftp_service_status import FTPServiceStatus
from openapi_client.models.mfa_status import MFAStatus
from openapi_client.models.services_status_defender import ServicesStatusDefender
from openapi_client.models.services_status_rate_limiters import (
    ServicesStatusRateLimiters,
)
from openapi_client.models.ssh_service_status import SSHServiceStatus
from openapi_client.models.web_dav_service_status import WebDAVServiceStatus


class ServicesStatus(BaseModel):
    """
    ServicesStatus
    """

    ssh: Optional[SSHServiceStatus] = None
    ftp: Optional[FTPServiceStatus] = None
    webdav: Optional[WebDAVServiceStatus] = None
    data_provider: Optional[DataProviderStatus] = None
    defender: Optional[ServicesStatusDefender] = None
    mfa: Optional[MFAStatus] = None
    allow_list: Optional[ServicesStatusDefender] = None
    rate_limiters: Optional[ServicesStatusRateLimiters] = None
    __properties = [
        "ssh",
        "ftp",
        "webdav",
        "data_provider",
        "defender",
        "mfa",
        "allow_list",
        "rate_limiters",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServicesStatus:
        """Create an instance of ServicesStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of ssh
        if self.ssh:
            _dict["ssh"] = self.ssh.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ftp
        if self.ftp:
            _dict["ftp"] = self.ftp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of webdav
        if self.webdav:
            _dict["webdav"] = self.webdav.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data_provider
        if self.data_provider:
            _dict["data_provider"] = self.data_provider.to_dict()
        # override the default output from pydantic by calling `to_dict()` of defender
        if self.defender:
            _dict["defender"] = self.defender.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mfa
        if self.mfa:
            _dict["mfa"] = self.mfa.to_dict()
        # override the default output from pydantic by calling `to_dict()` of allow_list
        if self.allow_list:
            _dict["allow_list"] = self.allow_list.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rate_limiters
        if self.rate_limiters:
            _dict["rate_limiters"] = self.rate_limiters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServicesStatus:
        """Create an instance of ServicesStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ServicesStatus.parse_obj(obj)

        _obj = ServicesStatus.parse_obj(
            {
                "ssh": SSHServiceStatus.from_dict(obj.get("ssh"))
                if obj.get("ssh") is not None
                else None,
                "ftp": FTPServiceStatus.from_dict(obj.get("ftp"))
                if obj.get("ftp") is not None
                else None,
                "webdav": WebDAVServiceStatus.from_dict(obj.get("webdav"))
                if obj.get("webdav") is not None
                else None,
                "data_provider": DataProviderStatus.from_dict(obj.get("data_provider"))
                if obj.get("data_provider") is not None
                else None,
                "defender": ServicesStatusDefender.from_dict(obj.get("defender"))
                if obj.get("defender") is not None
                else None,
                "mfa": MFAStatus.from_dict(obj.get("mfa"))
                if obj.get("mfa") is not None
                else None,
                "allow_list": ServicesStatusDefender.from_dict(obj.get("allow_list"))
                if obj.get("allow_list") is not None
                else None,
                "rate_limiters": ServicesStatusRateLimiters.from_dict(
                    obj.get("rate_limiters")
                )
                if obj.get("rate_limiters") is not None
                else None,
            }
        )
        return _obj
