# -*- coding: utf-8 -*-

"""
    SFTPGo

    SFTPGo allows you to securely share your files over SFTP and optionally over HTTP/S, FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per-user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, a user with the S3 backend mapping a Google Cloud Storage bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo supports groups to simplify the administration of multiple accounts by letting you assign settings once to a group, instead of multiple times to each individual user. The SFTPGo WebClient allows end users to change their credentials, browse and manage their files in the browser and setup two-factor authentication which works with Authy, Google Authenticator and other compatible apps. From the WebClient each authorized user can also create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date.

    The version of the OpenAPI document: 2.5.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
from openapi_client.models.tls_versions import TLSVersions


class WebDAVBinding(BaseModel):
    """
    WebDAVBinding
    """

    address: Optional[StrictStr] = Field(
        None, description="TCP address the server listen on"
    )
    port: Optional[StrictInt] = Field(
        None, description="the port used for serving requests"
    )
    enable_https: Optional[StrictBool] = None
    min_tls_version: Optional[TLSVersions] = None
    client_auth_type: Optional[StrictInt] = Field(
        None,
        description="1 means that client certificate authentication is required in addition to HTTP basic authentication",
    )
    tls_cipher_suites: Optional[conlist(StrictStr)] = Field(
        None,
        description="List of supported cipher suites for TLS version 1.2. If empty  a default list of secure cipher suites is used, with a preference order based on hardware performance",
    )
    prefix: Optional[StrictStr] = Field(
        None,
        description="Prefix for WebDAV resources, if empty WebDAV resources will be available at the `/` URI",
    )
    proxy_allowed: Optional[conlist(StrictStr)] = Field(
        None,
        description="List of IP addresses and IP ranges allowed to set proxy headers",
    )
    __properties = [
        "address",
        "port",
        "enable_https",
        "min_tls_version",
        "client_auth_type",
        "tls_cipher_suites",
        "prefix",
        "proxy_allowed",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WebDAVBinding:
        """Create an instance of WebDAVBinding from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WebDAVBinding:
        """Create an instance of WebDAVBinding from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WebDAVBinding.parse_obj(obj)

        _obj = WebDAVBinding.parse_obj(
            {
                "address": obj.get("address"),
                "port": obj.get("port"),
                "enable_https": obj.get("enable_https"),
                "min_tls_version": obj.get("min_tls_version"),
                "client_auth_type": obj.get("client_auth_type"),
                "tls_cipher_suites": obj.get("tls_cipher_suites"),
                "prefix": obj.get("prefix"),
                "proxy_allowed": obj.get("proxy_allowed"),
            }
        )
        return _obj
